a=input('enter name')
print(a)
print(a.capitalize())
print(a.casefold())
#print(a.count())
print(a.isalnum())
#print(a.isaplha())
print(a.join('abc'))
print(a.index('h'))
print(a.islower())
print(a.isspace())
print(a.endswith('i'))
print(a.find('4'))
print(a.isupper())
